### ISSUE TITLE
Spinning Wheel?

### ISSUE THREAD

**Issue by ralphschreyer** [adamhajari/spyre#11]
Hi Adam,

I have your great little framework up and running, thank you very much for this (btw, after changing "import View" to "import view" and "View.View()" to "view.View()" in server.py, since the view module is named view.py ...)

My little app takes some time to calculate after pressing some button - can I get some spinning wheel or something in order to show that the calculation is still going on and in order to prevent the button to be pressed again during calculation?

Thanks, cheers,

Ralph

**Comment by huntcsg** [comment]
Hi Ralph,

This functionality was recently added by Adam. Are you on Windows? I have noticed that when I serve my app locally from a windows platform that I do NOT get a spinning wheel, but when I serve my app from linux I DO get a spinning wheel. If you go to foolofgod.pythonanywhere.com, you can see what it looks like. I spent a little time trying to figure out the cause of this, but I'm unsure at the moment.

Cheers,

Hunter

**Comment by ralphschreyer** [comment]
Hi Hunter,

thanks a lot for your answer. Right, I'm serving from Windows - no choice, unfortunately, since I'm using spyre at work ... Could it be some system dependent path issue? I've exchanged the hard coded path construction with os.path.join and os.sep in the spyre code everywhere I could find it, but still don't get the wheel. By the way, looks nice on the link you've sent :-)

Cheers
Ralph

**Comment by adamhajari** [comment]
hi @ralphschreyer 
which version of spyre are you using?

**Comment by ralphschreyer** [comment]
Hi Adam,

I have to check when I'm back at work but I did pip install dataspyre some days ago and the code seemed to be in sync with GitHub ...

Thanks
Ralph

**Comment by adamhajari** [comment]
@ralphschreyer this issue has been fixed here: https://github.com/adamhajari/spyre/commit/961287035ee2f84742f4d63ca88b526d61e82168

**Comment by ralphschreyer** [comment]
Hi Adam,

great, works! Thanks a lot.

Ralph

2015-01-12 4:09 GMT+01:00 Adam Hajari <notifications@github.com>:
