### ISSUE TITLE
QPixmap: It is not safe to use pixmaps outside the GUI thread

### ISSUE THREAD

**Issue by adamhajari** [adamhajari/spyre#14]
Appears when matplotlib figures are loading on windows OS.

Proposed fix:
Add these two lines to the top of server.py
````
import matplotlib 
matplotlib.use('Agg') 
````

with this change, server should always be imported before matplotlib.

**Comment by adamhajari** [comment]
fixed here https://github.com/adamhajari/spyre/commit/2f4fe0e847ff99fd39ae5bec4e18b1ed1e2b854a as per this suggestion http://matplotlib.org/faq/howto_faq.html#matplotlib-in-a-web-application-server

**Comment by huntcsg** [comment]
Nice! Thanks!
