### ISSUE TITLE
Python 3 Support?

### ISSUE THREAD

**Issue by huntcsg** [adamhajari/spyre#2]
Hi Adam,

I just watched the video demo you gave of spyre posted by PyData on youtube. I am super excited about what spyre has to offer.

I was wondering if you have any desire to make it compatible with python 3, specifically python 3.4?

Is there anything that you can think of that technically would preclude spyre from being used in python 3.4?

I would love to contribute to an effort to make it compatible with python 3, if it's something that you would be amenable to.

**Comment by huntcsg** [comment]
Running the example_show_all_inputs.py, and working through the raised exceptions I've got the following so far:

* print statement vs. function (probably not an issue because the prints look like they were for debugging purposes. So they are probably not necessary to keep. If they are, some options include importing the print_function from __future__ or just wrapping the printed statement in parenthesis (e.g. "print item" becomes "print (item)"
* StringIO is no longer a module. It is now a class in the io module. So we could add an import conditioned on python version at the top of these files with "from io import StringIO"
* reload is now imp.reload, so we could do the same as above "from imp import reload", however the "sys.setdefaultencoding("utf-8") is now the default in python3 (I think), so we could add a condition based on the version. to do that in python2.
* dict.iteritems is now just dict.items, so long as you are iterating over it, so I'm not sure the best way to make this compatible.

If you are not personally particularly interested in making the project compatible with python 3, I can always maintain a fork that is either python 3 only, or python 2/python 3 compatible. Maybe as a first step I can do this (after reading up on some best practices, for instance [Porting Python 2 Code to Python 3](https://docs.python.org/3/howto/pyporting.html)). Then if it turns out that the task of keeping spyre compatible with Python is not too daunting, maybe we can just keep the canonical spyre compatible with both. Luckily cherrypy, matplotlib and pandas are all python3 compatible so I don't think we have an issue there in terms of package dependencies.

**Comment by huntcsg** [comment]
I was thinking the same thing!

**Comment by ianozsvald** [comment]
+1 for Python 3.4+ support please :-) IPython Notebook isn't good enough to export data science products to the web (mostly due to security leaks) and I want a good example of how to do this for an upcoming keynote (PyConSweden in May). I hope to demo Spyre and knowing it can use the future-proof version of Python (Py 2.7's sunset date is <5 years away now) is important.

**Comment by adamhajari** [comment]
@ianozsvald and @huntcsg python 3.4 support was added in the most recent commit.

**Comment by ianozsvald** [comment]
@adamhajari That's great to hear, I'll endeavour to cover this in my keynote - cheers :-)
