### ISSUE TITLE
"value" attribute not respected by dropdown input type

### ISSUE THREAD

**Issue by billywong9** [adamhajari/spyre#21]
Problem - "value" attribute is not respected by dropdown input

Example - 
{'variable_name':'shoe_size',
               'label':'Shoe size',
               'input_type':'dropdown',
               'options':[{'label':size,'value':size} for size in range(6,13)],
               'value':8,
               'action_id':'xxx'}

Result - First option (i.e. "6") is selected on page load

Expectation - Option "8" should be selected on page load

Solution - Change line 243 in view.html from
<code>
&lt;option value={{option['value']}}&gt;{{option['label']}}&lt;/option&gt;
</code>
to
<code>
&lt;option value={{option['value']}} {% if input['value']==option['value'] %}selected{% endif %}&gt;{{option['label']}}&lt;/option&gt;
</code>

**Comment by adamhajari** [comment]
@billywong9 this issue has been addressed [here](https://github.com/adamhajari/spyre/commit/5bd1be54cad129772a0b6541369cda64d2432492#diff-ccdc01a5d6dafc7ded81a18f9b8c7f5e) and [here](https://github.com/jjschultz/spyre/commit/e9b7f8c04f7e8618a9881a8d856c167151bbbdaa).
You can now either supply "checked" attribute with the option that should be selected by default (as you would do with the radiobuttons) or provide a "value" attribute on the input element as you've done above.
