### ISSUE TITLE
Add Options to display DataFrame Index 

### ISSUE THREAD

**Issue by sinhrks** [adamhajari/spyre#24]
Thanks for the great package!

Currently, ``spyre`` doesn't render ``DataFrame`` index by default. Is it reasonable to add an option to switch the behaviour?

- https://github.com/adamhajari/spyre/blob/master/spyre/server.py#L117

Also, there is a bug when a ``DataFrame`` has a named ``Index``. Pls see the below image which has unnecessary row.

```
from spyre import server

import numpy as np
import pandas as pd

idx = pd.Index(list('ABCDE'), name='index')
df = pd.DataFrame(np.random.randn(5, 5), index=idx)

class Example(server.App):

    tabs = ['example']
    outputs = [{"output_type" : "table",
                "output_id" : "table_id",
                "tab" : "example",
                "on_page_load" : True }]

    def getData(self, params):
        return df

app = Example()
app.launch(port=9093)
```

![2015-06-13 5 55 22](https://cloud.githubusercontent.com/assets/1696302/8139718/d6089a12-1190-11e5-98c0-5a12cc3e61c6.png)

**Comment by sinhrks** [comment]
Sorry, I found the latter bug is caused by ``pandas.DataFrame.to_html()`` side. I've issued pydata/pandas#10344.

What I would like to ask you in this issue is whether adding an option to draw ``Index`` is reasonable because ``Index`` can contain meaningful information such as ``datetime``.

**Comment by adamhajari** [comment]
@sinhrks couldn't you just call the .reset_index() method on the dataframe?

**Comment by sinhrks** [comment]
Possible as a workaround, but ``DataFrame.index`` often contain important information. I think it is better to always display ``index`` if there is no switching option.

**Comment by adamhajari** [comment]
@sinhrks i've addressed this issue [here](https://github.com/adamhajari/spyre/commit/3e4b6eda55b9a2aed90481b03016ed3be1cf167c) and [here](https://github.com/adamhajari/spyre/commit/1e27aa054b4af533b8d8b597ed3ff38e124756b6)

to include the index column in your tables put:
`server.include_df_index = True`
at the top of your app after you import the server class.

Example [here](https://github.com/adamhajari/spyre/blob/1e27aa054b4af533b8d8b597ed3ff38e124756b6/spyre/example_show_all_the_inputs.py)
