### ISSUE TITLE
Allow getPlot to return matplotlib.Axes or its np.array

### ISSUE THREAD

**Issue by sinhrks** [adamhajari/spyre#25]
Because ``pandas`` plotting functions return ``matplotlib.Axes`` or np.array of ``Axes`` in subplot case, it is nice if ``spyre`` can accept it.

- http://pandas.pydata.org/pandas-docs/stable/visualization.html

In these cases, we can get background figure using ``.get_figure``.

- https://github.com/adamhajari/spyre/blob/5f602f402e62e89b0e45995bed805b85c83ccaa5/spyre/model.py#L10

**Comment by adamhajari** [comment]
addressed [here](https://github.com/adamhajari/spyre/commit/f2af67b43450a1ccd1e099ca3263732195bfffe2)
