### ISSUE TITLE
bokeh html not rendering and getting unhelpful error message.

### ISSUE THREAD

**Issue by startakovsky** [adamhajari/spyre#30]
I have a bokeh plot which works perfectly on my vagrant machine...  Here's the bottom of the method which returns the html and some other methods I found which make it work nicely.

However, I get the not-too-helpful `**Override** the getHTML method to insert your own HTML here` exception when I try to view the graph on another machine on my company intranet.

Any guesses as to why this might be happening? I'm not sure if this is related to spyre or bokeh.  Feel free to delete if irrelevant. I've also posted this question here:  http://stackoverflow.com/questions/31915051/bokeh-html-not-rendering-on-company-server

    .
    .
    .

       script, div = components(p, INLINE)
        html = "%s\n%s"%(script, div)

        return html

    def getCustomJS(self):
        return INLINE.js_raw[0]

    def getCustomCSS(self):
        return INLINE.css_raw[0]

    app = MyApp()
    app.launch(port=9097,host='0.0.0.0')

**Comment by startakovsky** [comment]
I was able to fix my issue. I guess it would be nice to be able to run this in debug mode. I would be happy to help out in the development of this...?

**Comment by adamhajari** [comment]
@startakovsky could you provide the full script for an app that doesn't provide a stacktrace?

**Comment by startakovsky** [comment]
@adamhajari I’d have to dig it up — I’m pretty sure I solved the problem just by learning the source code a little more; out of curiosity, are you planning on furthering development of spyre? 

Steven

**Comment by adamhajari** [comment]
@startakovsky there are several places that could be improved with better exception handling. I'm not currently doing any major updates to spyre, but plan to address any bugs, minor feature requests, and PRs as they come in.
