### ISSUE TITLE
table width

### ISSUE THREAD

**Issue by rfieldhouse** [adamhajari/spyre#35]
Is there a quick way to change how wide tables are?

**Comment by adamhajari** [comment]
@rfieldhouse yep.
just add a `getCustomCSS` method to your app that returns whatever modifications/additions you want to make to a given css attribute:

```python
def getCustomCSS(self):
    return """table {width: 100%;}"""
```

Here's an example app that uses getCustomCSS: https://github.com/adamhajari/spyre/blob/master/examples/simple_sine_background_image_example.py
