### ISSUE TITLE
Changing a dropdown's option list programmatically

### ISSUE THREAD

**Issue by willgroves** [adamhajari/spyre#36]
I see in the examples that it is possible to link two input entities so that an assignment to one will also change the assignment of the other. I have a more general use case which may not be addressed by the code so far:

Given a tree of choices with two levels, I would like to choose an assignment using two dropdown inputs: i.e. (A,1), (A,2), (B,2), ... are possible assignments. The tree of possible values is below:

Level 1 -> Level 2
A           -> 1,2
B           -> 2,3,4
C           -> 1,2,...,100

Is it possible to change the values seen on the level 2 dropdown based on the assignment of level 1 using the linked inputs facility? Is there a recommended work-around for this kind of structure? 

Thanks,
Will

**Comment by adamhajari** [comment]
hey @willgroves thanks for the feedback. There's no way to do this currently, but I will consider adding this functionality in future updates (or you can send a PR if you have a simple way to do so already).

**Comment by VeenitShah** [comment]
@willgroves +1 for this feature. We would love to see this feature, too. Bokeh can do this easily.

@adamhajari would you have a time estimation for when this feature will be added? I've chosen spyre as a front end to my application as it's amazing and this missing feature is blocking a major release.

Thank you in advance.
Regards,
V
