### ISSUE TITLE
Uploading files

### ISSUE THREAD

**Issue by mendessoares** [adamhajari/spyre#39]
Is there a way to allow the user to upload the files that will be used in the app?

**Comment by etch32** [comment]
+1 for this question/request.  Would like to use the same app with multiple datasets. Fantastic framework, thank you!

**Comment by adamhajari** [comment]
@mendessoares and @etch32 I've just added this functionality. Check out this example for tips on getting started: https://github.com/adamhajari/spyre/blob/master/examples/user_upload_example.py

**Comment by mendessoares** [comment]
Awesome!

Maria H. Mendes Soares, Ph.D. | Postdoctoral Research Fellow | Department of Surgery | Center for Individualized Medicine | Microbiome Program | 507-284-0123 | soares.maria@mayo.edu
Mayo Clinic | 200 First Street SW | Rochester, MN 55905 | mayoclinic.org<http://www.mayoclinic.org/>

**Comment by mendessoares** [comment]
Can’t see the button…

Maria H. Mendes Soares, Ph.D. | Postdoctoral Research Fellow | Department of Surgery | Center for Individualized Medicine | Microbiome Program | 507-284-0123 | soares.maria@mayo.edu
Mayo Clinic | 200 First Street SW | Rochester, MN 55905 | mayoclinic.org<http://www.mayoclinic.org/>

**Comment by adamhajari** [comment]
@mendessoares what OS and browser are you using? I've tested on OSX with chrome, safari, and firefox. Can you send a screenshot.

**Comment by mendessoares** [comment]
OSX and Chrome

**Comment by adamhajari** [comment]
@mendessoares did you run 
```pip install --upgrade dataspyre```?
can you verify that you're on version 0.2.1 of spyre?

**Comment by mendessoares** [comment]
Success! Beautiful!



Sent via the Samsung Galaxy Note5, an AT&T 4G LTE smartphone


-------- Original message --------
