### ISSUE TITLE
Alternate Dashboards?

### ISSUE THREAD

**Issue by etch32** [adamhajari/spyre#40]
More of a request than an issue.

Currently the only option appears to be inputs on the left, outputs on the right. I understand complete flexibility (grid, various horizontal, vertical elements) may be out of the question but any plans on supporting a limited (3-5) set of dashboards?

**Comment by adamhajari** [comment]
@etch32 you have a lot of flexibility about page layout with the getCustomCSS method. You can check out the default css used here: https://github.com/adamhajari/spyre/blob/master/spyre/public/css/style.css
and override whatever elements you'd like to change. For instance, we could make a mobile friendly app by adding the following method to our app:

```python
    def getCustomCSS(self):
        css = """.menu {
                    position: static;
                    background: #FFFFFF;
                    width: 100%;
                    padding-left: 10%;
                    padding-right: 10%;
                }

                .content {      
                    float: left;
                    margin-left: 0
                }"""
        return css
```

Ideally we could add a "custom_layouts" directory to the project where anyone could add and share their own custom layouts.
