### ISSUE TITLE
Jupyter integration

### ISSUE THREAD

**Issue by joequant** [adamhajari/spyre#43]
Just to let you know, that I'm working on integrating jupyter and spyder.  The idea is that you will be able to prototype spyder in a jupyter window and then execute it such that you can get to it via another web address.

I'm using this with my docker image joequant/bitstation.

**Comment by adamhajari** [comment]
@joequant there's already a `launch_in_notebook` method. Have you tried this out? It's a little buggy so could definitely use some updates.
