### ISSUE TITLE
Add Authentication

### ISSUE THREAD

**Issue by jbrambleDC** [adamhajari/spyre#44]
It doesn't seem that there is an easy way to add authentication to a dashboard, or multi dash app. If there is please assist me?

**Comment by jbrambleDC** [comment]
@adamhajari Care to connect on this and discuss adding it?

**Comment by jbrambleDC** [comment]
closing due to lack of response from @adamhajari

**Comment by Dana-Farber** [comment]
Solved in https://github.com/adamhajari/spyre/pull/87 @jbrambleDC
