### ISSUE TITLE
Add a MultiSelect input

### ISSUE THREAD

**Issue by rs2** [adamhajari/spyre#51]
Akin the Multiselect IPython widget.

Please assign me to this issue.

**Comment by phlhayes** [comment]
@rs2 @adamhajari added here: https://github.com/phlhayes/spyre

**Comment by adamhajari** [comment]
merged with this PR: https://github.com/adamhajari/spyre/pull/63
see https://github.com/adamhajari/spyre/blob/master/spyre/tezt_app2.py for example use
