### ISSUE TITLE
How can I add an independent route?

### ISSUE THREAD

**Issue by fredthedead** [adamhajari/spyre#59]
In order to deploy my Spyre based app I am required to have a '/heartbeat' webpage that just returns some valid html.

How can I add that route to the app?

**Comment by gramster** [comment]
Here is what I did. Rather than use:

    if __name__ == "__main__":
        app = SimpleApp()
        app.launch(host='', port=8000)

I duplicated and customized the internals of app.launche:

    if __name__ == "__main__":
        app = SimpleApp()
        app.prefix = '/'
        webapp = app.getRoot()
        cherrypy.server.socket_host = '0.0.0.0'
        cherrypy.server.socket_port = 8000
        cherrypy.tree.mount(webapp, '/'). # Probably redundant
        cherrypy.quickstart(webapp, '/', {'/scripts': {
            'tools.staticdir.on': True,
            'tools.staticdir.dir': os.path.abspath('scripts')
        }})

In my case I wanted to be able to serve up additional scripts with a /scripts/ URL prefix. But you can do other things pretty easily too; refer to the CherryPy docs.

**Comment by adamhajari** [comment]
gramster's PR has been merged and included in version 0.2.8.
