### ISSUE TITLE
Improve Multiple Plots API

### ISSUE THREAD

**Issue by huntcsg** [adamhajari/spyre#6]
So, most dashboards I'd envision will have multiple tabs with multiple matplotlib/plots per tab. To clean this up a little, I've been writing functions in a separate file (maybe config.py or plots.py) that output either a matplotlib figure or the HTML associated with a bokeh plot.

Then in the app class definition I write the following:
    
    if params['output_id'] == 'output_1':
        return config.plot_func_1(params)
    if params['output_id'] == 'output_2':
        return config.plot_func_2(params)
    .
    .
    .
    if params['output_id'] == 'output_n':
        return config.plot_func_n(params)

A simple improvement would be to create a server.App class method that takes the output id, the return function and the params and either returns the result of the function or passes. Something like this:

    def output(output_id, func, params, *args, **kwargs):
        if params['output_id'] == output_id:
            return func(params, *args, **kwargs)
        else:
            pass

Which in the above example would look like this:

    self.output('output_1', get_plot_1, params)
    self.output('output_2', get_plot_2, params)
    .
    .
    .
    self.output('output_n', get_plot_n, params)

I think the main benefit would be that you aren't crowding up the app definition with lots of conditionals and return statements.

My python skills are not fantastic, but I am also beginning to imagine the use of decorators to define output functions.

So in my config.py file where I am defining all my plots I would be able to do the following:

    @output('output_1', 'getPlot')
    def get_plot_1(params)
        #My Plot Code
        return figure

    @output('output_2', 'getHTML')
    def get_plot_2(params):
        #My HTML Code
        return html

And then the respective getXXXX methods would be populated accordingly.

I'm not really sure how we would implement the above, but I guess one question is whether this would be useful. The second question would be whether this is a good interface.

Your thoughts? I'd be happy to work on implementing the first part if there is interest. As far as the second part we'd have to flesh out the details and then look into implementation.

**Comment by adamhajari** [comment]
@huntcsg I think there's an even cleaner way to do this.

If we make this the default getPlot method

````
def getPlot(self, params):
	return eval("self."+str(params['output_id'])+"()")
````

Then you can either override getPlot (the normal way), or if you want multiple plots, leave getPlot as is and create a new function for each plot output element:

````
def output_1(self, params):
    #code to generate a plot
    return figure

def output_2(self, params):
    #code to generate a different plot
    return figure
````

We can do the same thing with getHTML, getData, etc...

Should be straight forward to implement. I'll work on it this week.

**Comment by huntcsg** [comment]
That's a nice idea! 

Just to confirm, with this method you would need to name your function the same thing as the output id, correct? That seems like a reasonable requirement. And it does away with the conditionals. Yay!

Also, I don't know if eval is better or worse than getattr, but I think you could also do

    def getPlot(self,params):
        return getattr(self, params['output_id'])(params)

Something about code generation scares me :)

**Comment by adamhajari** [comment]
issue addressed with this commit: https://github.com/adamhajari/spyre/commit/d46aca1782b48e534de103d9df5bbbb23bcf454b

**Comment by huntcsg** [comment]
Thanks!
