### ISSUE TITLE
TextBox in Spyre

### ISSUE THREAD

**Issue by jaganadhg** [adamhajari/spyre#85]
Hi Team,
Is there any way to adjust the height and width of the text box. I tried height etc as kwargs. But not effective. I am trying to display text box bit bigger to enter free flow text

Best

Jagan

**Comment by adamhajari** [comment]
these attributes are defined as css here: https://github.com/adamhajari/spyre/blob/master/spyre/public/css/style.css

you can overwrite any of these elements by adding the:

```def getCustomCSS(self):```

method to your app class. `getCustomCSS()` should return a string of css elements that you want to define. this css gets loaded _after_ the default spyre css so anything you define here will overwrite css already defined in https://github.com/adamhajari/spyre/blob/master/spyre/public/css/style.css

the textbox style attributes are defined as part of `input` element on line 26:
```input {
	display: block;
	padding: 5px;
	margin: 5px 0 0;
	font-size: 14px;
	font-family: Arial, Helvetica, sans-serif;
        height: 50px;
	width: 100%;
	box-sizing: border-box;  /* Ensures that the input will not extend past the input panel */
}
```

to increase the height of the text box you can add this element to the string returned by `getCustomCSS()` but with a different height value:

```def getCustomCSS(self):
        css = """
            input {
                display: block;
                padding: 5px;
                margin: 5px 0 0;
                font-size: 14px;
                font-family: Arial, Helvetica, sans-serif;
                width: 100%;
                box-sizing: border-box;
            }
        """
        return css
```

As you can see the width is already set to 100% of the left panel so to increase the width you need to increase the width of the left panel and increase the margin of the right panel. You would do that by including custom `.menu` and `.content` elements to the string returned by `getCustomCSS`.

**Comment by adamhajari** [comment]
see example here: https://github.com/adamhajari/spyre/blob/master/examples/simple_sine_background_image_example.py
